### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.concurrent.ConcurrentHashMap$KeySetView

### ISSUE THREAD

**Issue by murselturk** [Ekito/koin#43]
Hi,

This is a great library. However I am getting the following error after the update to 0.8.1, if I run in a device with SDK 16:

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.NoClassDefFoundError: java.util.concurrent.ConcurrentHashMap$KeySetView
                                                                         at org.koin.core.instance.InstanceFactory.findInstance(InstanceFactory.kt:45)
                                                                         at org.koin.core.instance.InstanceFactory.retrieveInstance(InstanceFactory.kt:27)
                                                                         at org.koin.KoinContext.resolveInstance(KoinContext.kt:70)
                                                                         at com.murselturk.radyo7.ui.base.BaseActivity$$special$$inlined$inject$1.invoke(AndroidExt.kt:106)
                                                                         at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)`

Any ideas what to do?
Thanks.

**Comment by arnaudgiuliani** [comment]
Hello,

the upgrade of Kotlin in `1.2.21` effectively broke the API of our instance registry and make it like it were in jdk 8.

I'll fix it for 0.8.2 👍

**Comment by m-ivanov** [comment]
In android in broken below API level 24

**Comment by murselturk** [comment]
I've also test in a device with SDK 22 and had no error messages. Maybe below API Level 21

**Comment by m-ivanov** [comment]
i desumed 21 from KeySetView  android docs, but tested on Api 19 emulator with the same crash, i it can help i can provide my gradle

**Comment by arnaudgiuliani** [comment]
Can you try the `0.8.2-alpha-14`?

**Comment by murselturk** [comment]
Works like a charm now :)

**Comment by arnaudgiuliani** [comment]
Nice. I push it to `0.8.2` thanks !

**Comment by arnaudgiuliani** [comment]
Don't hesitate if you see problem like this one 👍

**Comment by richardroche** [comment]
Thank you so much for being so proactive
